Fix for #17
concourse/hg-resource pull request #18
Opened 2021-03-09 17:06 UTC by s2hc-johan

Fixed ubuntu docker file and ssh dir issue

Created a function, based on the old atomicSave, that creates the `.ssh`
dir.

This should close #17, I'm not that fluent in golang, and I don't really know how I would setup ssh to be able to test. But we built an image and our pipeline works with it.

2021-03-11 22:19 UTC, xtremerui commented
Thx for submitting the PR. Would you be able to add a test for the `mkSSHDir` function? You could follow the example of `startSshAgent ` https://github.com/concourse/hg-resource/blob/f50064ed4a8eca504233dab7712f4455105dd291/hgresource/ssh_test.go#L36

to invoke the function and assert on the result whether the dir is created correctly. So it'd be sth like
```
Context : when making ssh dir {
    It should create the dir {
         mkSSHDir(some-dir)
        
       Expect some-dir is created
    }
}
```
you dont need to start up ssh agent for this unit test.

2021-03-12 16:31 UTC, xtremerui commented on hgresource/ssh_test.go
> +	sshClientConfigFile := path.Join(homeDir, ".ssh/config")
```suggestion
```

these could be moved inside the context.

2021-03-12 16:32 UTC, xtremerui commented on hgresource/ssh_test.go
> +		It("can crete the directory", func() {
```suggestion
	homeDir := "/tmp"
	sshDir := path.Join(homeDir, ".ssh")
	sshClientConfigFile := path.Join(homeDir, ".ssh/config")
	
		It("can crete the directory", func() {
```

2021-03-12 16:32 UTC, xtremerui commented on hgresource/ssh_test.go
> +	Context("When configuring ssh", func() {
```suggestion
	Context("When configuring ssh", func() {
		homeDir := "/tmp"
	        sshDir := path.Join(homeDir, ".ssh")
	        sshClientConfigFile := path.Join(homeDir, ".ssh/config")
```

2021-03-12 16:33 UTC, xtremerui commented on hgresource/ssh_test.go
> +			Expect(err).To(BeNil())
```suggestion
```

2021-03-12 16:34 UTC, xtremerui commented on hgresource/ssh_test.go
> +			Expect(err).To(BeNil())
```suggestion
```
this could be move the an afereach

2021-03-12 16:35 UTC, xtremerui commented on hgresource/ssh_test.go
> +
```suggestion
AfterEach(func()  {
                        // cleanup
			err = os.RemoveAll(sshDir)
			Expect(err).To(BeNil())
})
```

2021-03-12 16:37 UTC, xtremerui requested changes
thx for the test. Just some refactors then we are good to go.

2021-03-12 17:12 UTC, s2hc-johan commented
I'll update with a new commit. `AfterEach` be before or after the `It` functions?

2021-03-12 17:18 UTC, s2hc-johan commented
seemed to work with before.

2021-03-15 07:46 UTC, s2hc-johan commented
I can't really follow why the CI failed. The docker commands builds for me locally

2021-03-15 14:19 UTC, xtremerui commented
we are reorganizing the github team configure and thus affects the CI. I will rerun it when CI is stable.

2021-03-15 16:11 UTC, merged